# Generated by Django 4.2.7 on 2023-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='категория')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена за покупку')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('change_date', models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения')),
            ],
        ),
    ]
