# Generated by Django 4.2.7 on 2023-11-18 14:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_load', verbose_name='изображение'),
        ),
    ]
