# Generated by Django 4.2.7 on 2023-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TextField(blank=True, null=True, verbose_name='для удаления'),
        ),
    ]
