# Generated by Django 4.2.7 on 2023-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number_views',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='просмотры'),
        ),
    ]
