# Generated by Django 4.2.7 on 2023-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0004_alter_blog_number_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='просмотры'),
        ),
    ]
