# Generated by Django 4.2.7 on 2024-01-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0005_alter_blog_number_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_hw192.product', verbose_name='продукт')),
            ],
        ),
    ]
