# Generated by Django 4.2.7 on 2024-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='url', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
