# Generated by Django 4.2.7 on 2024-01-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_hw192', '0007_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_version', models.CharField(max_length=100, verbose_name='название версии')),
                ('number_version', models.CharField(max_length=100, verbose_name='номер версии')),
                ('newest_version', models.BooleanField(default=True, verbose_name='признак новейшей версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_hw192.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
